version: '3'
services:
  react-app:
    container_name: fuel-panel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:3000"
    volumes:
      - .:/app
    stdin_open: true
